### PR TITLE
Fix Code Re-Struture Project #26

### PR DESCRIPTION
**Pull request by madhur87**
Please Review and Merge @ZapeeoSheikh, @tusharzalte 

#26

### CODE REVIEW

**Comment by ZapeeoSheikh** [comment]
@madhur87  Resolve Conflicts

**Review by ZapeeoSheikh — COMMENTED** [review]
Reviewed

**Comment by madhur87** [comment]
@ZapeeoSheikh Conflicts Resolve

**Comment by madhur87** [comment]
Can you Merge please @ZapeeoSheikh

**Comment by madhur87** [comment]
Is there any particular reason, why you not merged the MR. @ZapeeoSheikh

**Pull request closed without merging**
