### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by karthiknadar1204**
changes proposed by @shravan-das 
please review @tusharzalte under #48

### CODE REVIEW

**Comment by karthiknadar1204** [comment]
@tusharzalte

**Comment by tusharzalte** [comment]
Yes

**Comment by karthiknadar1204** [comment]
@tusharzalte Please add a label

**Comment by karthiknadar1204** [comment]
@ZapeeoSheikh Please add gssoc label to the issue as wel as the pr, its been many days, i have been requesting but no response

**Pull request merged**
