### PR TITLE
Inline validation in login-signup

### LINKED ISSUE #150: [FEATURE] Inline Validation in Login and Register Form
## Current Feature
Currently, on submitting the registration form with invalid input the only message user receives is **Registration fail**. This does not give a proper description to the user that what makes the registration fail.

## Better Feature
In the Register and login forms, there is no real-time validation message that appears when the user type in the message. I want to make the validation messages appear as the user fills in the forms. If the constraints are not met the message stays and the user will not be able to submit the form but as soon as the valid input is given the message disappears and the forms can be submitted. This kind of real-time validation will provide a better user experience.

### Screenshots

I want to implement functionality similar to the one shown in the below video:

https://github.com/tusharzalte/tusharesume/assets/86224794/32af7c6e-4349-4c9e-a819-1e22dcf60a4b

If you find this feature worth implementing please assign this issue to me under the GSSOC'23 label as I am a GSSOC Contributor.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by AlfiyaSiddique**
## Description
Added inline validation in login and Register Form

##  Fixes Issue #150 **Inline Validation in Login and Register Form**
        
closes #150 

## Sample Output

https://github.com/tusharzalte/tusharesume/assets/86224794/d7619453-86b4-4e75-8e3a-fc5a99bbc681

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
@ZapeeoSheikh please review this PR!!

**Comment by AlfiyaSiddique** [comment]
Hey @tusharzalte can you please review this PR!

**Comment by AlfiyaSiddique** [comment]
Hello @ZapeeoSheikh 
I request you to review and merge this PR!!

**Comment by AlfiyaSiddique** [comment]
Hey @ZapeeoSheikh 

Please review this PR!!

**Comment by ZapeeoSheikh** [comment]
@AlfiyaSiddique There are lot of conflicts in this pr.

**Comment by ZapeeoSheikh** [comment]
You can reopen it if you want

**Comment by AlfiyaSiddique** [comment]
Hello @ZapeeoSheikh 

I'll resolve the merge conflict and make a commit soon, then please merge my PR

**Comment by AlfiyaSiddique** [comment]
Hey @ZapeeoSheikh 

I have resolved the conflicts. I cannot reopen this PR as it is closed by you. 
So,  Please Reopen this PR so that the latest changes can be accepted or else I have to create a new PR.

**Comment by AlfiyaSiddique** [comment]
Hey @ZapeeoSheikh , Should I create a new PR or will you reopen this PR?  Because I'm unable to reopen it

**Pull request closed without merging**
