### PR TITLE
Fix Code Structure

### PR DESCRIPTION
**Pull request by madhur87**
Fix Code Structure with Latest Code #26,

Please review and merge @ZapeeoSheikh

### CODE REVIEW

**Comment by ZapeeoSheikh** [comment]
Please resolved conflicts

**Comment by madhur87** [comment]
Done, Please Merge ASAP, @ZapeeoSheikh

**Comment by ZapeeoSheikh** [comment]
I am not able to merge as it is still showing conflicts error

**Comment by madhur87** [comment]
Done, Please Merge first, @ZapeeoSheikh

**Pull request merged**
