### PR TITLE
#92 Bot Added

### LINKED ISSUE #92: [FEATURE] Add close old issue bot
### Description

"By incorporating a bot that automatically closes old and inactive issues, we can ensure better issue management and keep the project organized."

"The bot's ability to identify and close outdated issues will streamline the issue tracking process, allowing the project team to focus on active and relevant tasks."

"Implementing an automated closing bot will help maintain a clean and up-to-date issue tracker, improving overall project efficiency and ensuring that active issues receive proper attention."

### Screenshots

_No response_

### Additional information

Assign this to me under GSSOC ' 23

generally we close issue that has not been responded for 30 days
let me know your preferred days :)

### PR DESCRIPTION
**Pull request by k-deepak04**
I have also restructured the code greeting bot was inside of issue template maybe i didn't noticed last time so changed that too

name: Pull Request Template

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pr-template:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR title
        run: |
          title=$(git log --pretty=format:%s origin/main..HEAD)
          if [[ $title != *"JIRA-"* ]]; then
            echo "Error: PR title must include a JIRA ticket number"
            exit 1
          fi

      - name: Check PR description
        run: |
          description=$(git log --pretty=format:%b origin/main..HEAD)
          if [[ $description != *"JIRA-"* ]]; then
            echo "Error: PR description must include a JIRA ticket number"
            exit 1
          fi

      - name: Request more information
        run: |
          echo "👋 Thank you for your contribution! To help the reviewer understand your changes better, please provide the following information:"

          echo ""
          echo "## Description"
          echo ""
          echo ""
          echo ""

          echo "## Why This PR ?"
          echo ""
          echo ""
          echo ""

          echo "## How Has This Been Tested?"
          echo ""
          echo ""
          echo ""

          echo "## Screenshots (if applicable)"
          echo ""
          echo ""
          echo ""

          echo "## Related Issues"
          echo "" closes #92 
          echo ""
          echo ""

          echo "## Types of Changes"
          echo ""
          echo ""
          echo "- [ ] Bug fix (non-breaking change which fixes an issue)"
          echo "- [x] New feature (non-breaking change which adds functionality)"
          echo "- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)"
          echo "- [ ] Documentation update"
          echo ""

          echo "## Checklist"
          echo ""
          echo ""
          echo "- [x] My code adheres to the established style guidelines of this project"
          echo "- [x] I have conducted a self-review of my code"
          echo "- [x] I have commented my code, particularly in hard-to-understand areas"
          echo "- [x] I have made corresponding changes to the documentation"
          echo "- [x] My changes generate no new warnings"
          echo ""

### CODE REVIEW

**Comment by k-deepak04** [comment]
closes #92

**Comment by tusharzalte** [comment]
Is project working nicely?

**Comment by k-deepak04** [comment]
@ZapeeoSheikh on the issue it was level 2 label you have added label 1 on the PR

**Comment by k-deepak04** [comment]
@ZapeeoSheikh @tusharzalte please update the label as this one is also not counted and if possible 
add level 2 as it comes under the integration part and while assigning label2 tag was assigned on this :)

**Comment by k-deepak04** [comment]
hey i read on the discord 
the proper label is gssoc23 
please add that on the pr so that it would be counted 
Also change labels for all as the issue is with me others contribution may also be not counted due to the capital label

**Comment by k-deepak04** [comment]
@tusharzalte @ZapeeoSheikh @madhur87 @Avinash905 anyone please do the necessary changes 
so that my contribution will count

**Comment by k-deepak04** [comment]
please assign small gssoc label

**Pull request merged**
