### PR TITLE
Inline validation

### LINKED ISSUE #150: [FEATURE] Inline Validation in Login and Register Form
## Current Feature
Currently, on submitting the registration form with invalid input the only message user receives is **Registration fail**. This does not give a proper description to the user that what makes the registration fail.

## Better Feature
In the Register and login forms, there is no real-time validation message that appears when the user type in the message. I want to make the validation messages appear as the user fills in the forms. If the constraints are not met the message stays and the user will not be able to submit the form but as soon as the valid input is given the message disappears and the forms can be submitted. This kind of real-time validation will provide a better user experience.

### Screenshots

I want to implement functionality similar to the one shown in the below video:

https://github.com/tusharzalte/tusharesume/assets/86224794/32af7c6e-4349-4c9e-a819-1e22dcf60a4b

If you find this feature worth implementing please assign this issue to me under the GSSOC'23 label as I am a GSSOC Contributor.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by AlfiyaSiddique**
## Description
**name: Inline Validation in Login Signup Form**
This pull request implements the code for adding inline validation in both signup and login form.

on: 18-06-2023

## Solves Issue
#150 [FEATURE] Inline Validation in Login and Register Form
closes #150 

## Sample Output Video

https://github.com/tusharzalte/tusharesume/assets/86224794/bd417e65-0416-4a76-b886-f1fdc34be061

## Request
I request you to add gssoc labels on this PR after you merged it!

### CODE REVIEW

**Comment by AlfiyaSiddique** [comment]
Hello @ZapeeoSheikh.
Please review this PR!

**Comment by AlfiyaSiddique** [comment]
@ZapeeoSheikh please review this PR!!

**Comment by AlfiyaSiddique** [comment]
Hello @ZapeeoSheikh 
Please review this PR!

**Comment by AlfiyaSiddique** [comment]
Hello @ZapeeoSheikh 
Please review this PR

**Comment by AlfiyaSiddique** [comment]
@ZapeeoSheikh please review this PR!!

**Comment by AlfiyaSiddique** [comment]
@ZapeeoSheikh Please review this PR!!

**Comment by AlfiyaSiddique** [comment]
@ZapeeoSheikh please review this PR!!

**Comment by AlfiyaSiddique** [comment]
Hey @ZapeeoSheikh , please review this PR!!

**Comment by AlfiyaSiddique** [comment]
@ZapeeoSheikh please review this PR

**Comment by AlfiyaSiddique** [comment]
@tusharzalte or @ZapeeoSheikh , can any one of you please review this PR before 10 August!!
 Because the points and PRs are not counted after that.

Please review this PR!!

**Comment by AlfiyaSiddique** [comment]
@tusharzalte OR @ZapeeoSheikh  ??

**Comment by ZapeeoSheikh** [comment]
@AlfiyaSiddique Extremely sorry for my busy schedule. Thank you for contributing.

**Comment by AlfiyaSiddique** [comment]
> @AlfiyaSiddique Extremely sorry for my busy schedule. Thank you for contributing.

No problem at all. Was mentioning you again and again just to remind you.  Thanks for you efforts. Let's keep up the good work. 🙌🏻

**Pull request merged**
