### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by karthiknadar1204**
The folder in the codebase is named client1 but in the readme it is client, it shows directory not found error when you copy the command from the readme and run in terminal so fixed it

### CODE REVIEW

**Comment by karthiknadar1204** [comment]
Clears issue #48 under gssoc'23 @tusharzalte

**Comment by karthiknadar1204** [comment]
@tusharzalte Done

**Comment by shravan-das** [comment]
also you can add the command node server.js for initializing backend server in readme file (not mentioned in readme file)

**Comment by karthiknadar1204** [comment]
Will do @shravan-das

**Comment by karthiknadar1204** [comment]
Please check #63 as well under gssoc including this

**Comment by ZapeeoSheikh** [comment]
LGTM 🚢

**Comment by gurjeetsinghvirdee** [comment]
Hey @ZapeeoSheikh 
Add the Appropriate labels in the PR's

Screenshot 2023-06-28 021647

**Comment by shravan-das** [comment]
Yesss please @ZapeeoSheikh /\

**Pull request merged**
